#!/bin/bash

authfile=FIXME
project=FIXME
numnodes=64
zone=us-west1-a
machinetype=n1-standard-8

test -f config.sh && source config.sh

die() {
    echo "ERROR: $*" 1>&2
    exit 1
}

cmd_buildlocal() {  # build o4extract container locally
    set -e
    (cd ../.. && git archive HEAD --prefix=ocropus4/ -o training/runextract/docker/ocropus4.tar.gz)
    (cd docker && docker build -t o4extract .)
}

cmd_build() {  # build and push container
    cmd_buildlocal
    docker tag o4extract tmbdev/o4extract
    docker push tmbdev/o4extract
    docker tag o4extract gcr.io/$project/o4extract
    docker push gcr.io/$project/o4extract || 
        die "did you run: 'gcloud auth configure-docker'?"
    }

cmd_indocker() {  # run a command inside the docker container on local machine
    docker run -i --rm -v $(pwd):/work \
        -v "$authfile":/auth.json -w /work -t o4extract "$@"
}


cmd_gcestart() {  # start a GCE cluster
    test $authfile = FIXME && die "must define authfile= in config.sh"
    test $project = FIXME && die "must define project= in config.sh"
    gcloud config set project $project
    gcloud config set compute/zone $zone
    gcloud container clusters create o4extract \
        --machine-type=$machinetype \
        --scopes storage-rw,compute-rw \
        --num-nodes=$numnodes --local-ssd-count 1
            gcloud container clusters get-credentials o4extract
}

cmd_gcestop() {
    yes | gcloud container clusters delete o4extract
}


cmd_gcesubmit() {
    kubectl delete pods --all
    gsutil ls gs://nvdata-ocropus/tess/ |
    fgrep .tar | sed 's!.*/!!' | cat -n | sed "${limit:-9999}q" |
    while read i n; do
        echo === $i $n
        sed "s/{{.Index}}/$i/g;s/{{.Item}}/$n/g" extractjob.yml > extract_$i.yml
        kubectl apply -f extract_$i.yml
        rm -f extract_$i.yml
        sleep 3
    done
}

cmd_gcemonitor() {
    watch 'kubectl get pods | awk "!/STATUS/{print \$3}" | sort | uniq -c'
}

cmd_allpods() {  # execute command in all running pods
    kubectl get pods | awk '$3=="Running"{print $1}' | 
    while read pod; do
        kubectl exec $pod -- "$@"
    done
}


cmd="${1:-help}"
shift

set -e

case $cmd in
    help)
        echo; echo available commands:; echo
        grep '^cmd_[_0-9a-z]*() {' "$0" | sed 's/cmd_//;s/\(.*\)() *{* *#* */\1 -- /'
        ;;
    *)
        set -e
        eval "cmd_$cmd" "$@"
        ;;
esac
