#!/bin/bash
library=$1
shift

python3=${python3:-python3}

help() {
cat <<EOF
Usage: $0 [COMMAND] [--help] ...

COMMAND:

EOF

grep '^[a-z_*-]*[)] *#' $0 | sed 's/[)] *[#]/ -- /'

echo
type python3
}

if test -d ./venv; then
    source ./venv/bin/activate
fi

case $library in

# data extraction

extract-seg)  # extract segmentation for training segmenters
    $python3 -m ocrlib.extract_seg "$@"
    ;;
extract-rec)  # extract images for training recognizers
    ;&
extract-lines)
    $python3 -m ocrlib.extract_lines "$@"
    ;;

# inference

ocroseg)  # page segmentation
    $python3 -m ocrlib.ocroseg "$@"
    ;;
ocrotext)  # line/word recognition
    ;&
ocroline)
    $python3 -m ocrlib.ocroline "$@"
    ;;
ocrobin)   # binarization
    $python3 -m ocrlib.ocrobin "$@"
    ;;
ocrorot)   # page rotation/orientation detection
    $python3 -m ocrlib.ocrorot "$@"
    ;;
ocroskew)   # skew estimation
    $python3 -m ocrlib.ocroskew "$@"
    ;;
ocroscale)   # scale estimation
    $python3 -m ocrlib.ocroscale "$@"
    ;;
nlbin)  # nonlinear binarization
    $python3 -m ocrlib.nlbin "$@"
    ;;
slog)  # examine logs
    $python3 -m ocrlib.slog "$@"
    ;;
wordrec)  # recognize pages
    $python3 -m ocrlib.wordrec "$@"
    ;;
pagerec)  # recognize pages
    $python3 -m ocrlib.pagerec "$@"
    ;;

# help

*)
    help
    ;;
esac
