#!/bin/bash
library=$1
shift

python3="${python3:-python3} ${OCROPUS_OPTS}"

help() {
cat <<EOF
Usage: $0 [COMMAND] [--help] ...

COMMAND:

EOF

grep '^[a-z_*-]*[)] *#' $0 | sed 's/[)] *[#]/ -- /'

echo
type python3
}

#if test -d ./venv; then
#    source ./venv/bin/activate
#fi

case $library in

# data extraction

seginf)  # recognize pages with layout information
    $python3 -m ocropus.seginf "$@"
    ;;
preinf)  # recognize pages with layout information
    $python3 -m ocropus.preinf "$@"
    ;;
segtrain)  # recognize pages with layout information
    $python3 -m ocropus.segtrain "$@"
    ;;
texttrain)  # recognize pages with layout information
    $python3 -m ocropus.texttrain "$@"
    ;;
textgen)  # recognize pages with layout information
    $python3 -m ocropus.textgen "$@"
    ;;
models)  # list and show models
    $python3 -m ocropus.models "$@"
    ;;
genwords)  # generate word images
    $python3 -m ocropus.genwords "$@"
    ;;
pdfproc)  # render and process PDF files
    $python3 -m ocropus.pdfproc "$@"
    ;;
misc)  # miscellaneous functions
    $python3 -m ocropus.misc "$@"
    ;;

# help

*)
    help
    ;;
esac
