# FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel
# RUN conda update conda
# RUN conda install python=3.9 -y
# FROM ubuntu:20.04
FROM nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qqy update

RUN apt-get install -qqy curl gcc openssh-client git
RUN apt-get install -qqy iputils-ping dnsutils parallel
RUN apt-get install -qqy apt-transport-https lsb-release gnupg apt-utils

ENV TZ="America/Los Angeles"
RUN echo \$TZ > /etc/timezone
RUN rm -f /etc/localtime && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime || true
RUN apt-get install -qqy tzdata

RUN apt-get install -qqy jq libmpack-dev net-tools expect
RUN apt-get install -qqy python3 python3-pip python3-dev python3-setuptools python3-zmq

#RUN apt-get install -qqy python-dev python-setuptools python-pip
RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
RUN mkdir -p /usr/local/gcloud && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz
RUN /usr/local/gcloud/google-cloud-sdk/install.sh

ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin

RUN apt-get install -qqy vim-nox

RUN pip3 install simplejson braceexpand msgpack matplotlib
RUN pip3 install setuptools
RUN pip3 install braceexpand bs4 click editdistance future lxml typer
RUN pip3 install matplotlib scikit-image scipy
# RUN pip3 install torch torchvision
RUN pip3 install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
RUN pip3 install tensorboard
RUN apt-get install -qqy wamerican-large
RUN apt-get install -qqy tesseract-ocr-all
RUN apt-get install -qqy python3-pip
RUN pip3 install dtrx
RUN pip3 install virtualenv

RUN mkdir /work
WORKDIR /work
RUN virtualenv venv && \
    . venv/bin/activate && \
    pip3 install -U braceexpand bs4 click editdistance lxml matplotlib \
        scikit-image scipy torch torchvision typer

RUN apt-get install -qqy rename
