#!/bin/bash

docker run -t -i \
    -e vol=$1 \
    -v $(pwd)/research-191823-cd9b98467446.json:/key.json \
    -w /work \
    tess \
    /bin/bash -c '
set -e
basedir="$(pwd)"
echo === $vol
result=cdip_$vol
source /usr/local/google-cloud-sdk/path.bash.inc
gcloud auth activate-service-account --key-file /key.json
gsutil cp gs://lpr-cdip/images.$vol.cpio volume.cpio
rm -rf volume outputs $result $result.tgz
dtrx --one rename volume.cpio
echo num_tiff $(find volume -name "*.tif" | wc -l)
rm -rf outputs
mkdir outputs
find volume -name "*.tif" | parallel -j 1 gm convert {} +adjoin outputs/{/.}-%04d.png
echo num_png $(find outputs -name "*.png" | wc -l)
exit
cd $basedir/outputs
# --oem 0 (original), 1 (lstm), 2 (both), 3 (auto default)
ls *.png | parallel --joblog ../LOG -j 1 ../run-tess --oem 1 {} {.} -l eng hocr
cd $basedir
test -d outputs
mv outputs $result
tar --sort=name -zcf $result.tgz $result
gsutil cp $result.tgz gs://lpr-cdip-tess/$result.tgz
# break
rm -rf volume outputs $result $result.tgz
'
