#!/bin/bash

cat > Dockerfile <<EOF
FROM ubuntu:18.04
RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:alex-p/tesseract-ocr
RUN apt-get update && apt-get install -y tesseract-ocr-all 
RUN mkdir /work
WORKDIR /work
EOF
sudo apt-get install -y dtrx rename parallel imagemagick
docker build -t tess - < Dockerfile

cat > run-tess <<\EOF
#!/bin/bash
docker run -v $(pwd):/work -w /work -t tess tesseract "$@"
EOF

chmod 755 run-tess

basedir="$(pwd)"

for vol in {0000..0999}; do
    cd $basedir || exit 1
    gsutil cp gs://lpr-g1000/Volume_$vol.tgz volume.tgz
    rm -rf volume outputs
    dtrx --one rename volume.tgz
    mkdir outputs
    cp volume/*.JPEG outputs/.
    ls outputs/*.JPEG | wc -l
    cd $basedir/outputs || exit 1
    test -f Image_0000.JPEG || exit 1
    ls *.JPEG | parallel --joblog ../LOG -j 4 ../run-tess --oem 1 {} {.} -l eng hocr
    cd $basedir || exit 1
    test -d outputs || exit 1
    mv outputs Volume_$vol &&
    tar --sort=name -zcf Volume_$vol.tgz Volume_$vol &&
    gsutil cp Volume_$vol.tgz gs://lpr-g1000-tess/Volume_$vol_tess.tgz
    rm -rf volume outputs Volume_$vol Volume_$vol.tgz
done
