#!/bin/bash

docker run -ti \
    -u $(id -u):$(id -g) \
    -v /etc/passwd:/etc/passwd \
    -v /etc/group:/etc/group \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME:$HOME \
    -v /sdata:/sdata \
    -v $(pwd):/work \
    -w /work \
    --net host \
    -e DISPLAY=$DISPLAY \
    ocropus4 \
    ${cmd:-ocropus4} "$@"
